spring:
  application:
    name: TravelAgency

  # налаштування підключення до PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: annasovhyria
    password:
    driver-class-name: org.postgresql.Driver

  # налаштування Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml

  # налаштування Hibernate (JPA)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/travel-realm